language: scala
scala:
  - "2.10.4"
  - "2.11.1"
  - "2.12.0"
jdk:
  - oraclejdk8
script: sbt ++${TRAVIS_SCALA_VERSION} test
env:
  global:
    - secure: "U0Nvkrz3X123a2zC8NbzOxSjEoori/wInvjHU5OYhnPxiPJ2ELo1FQVQlEUmbPihyw+Sx80TP/ARzZNIzq037VcGK6dm+ygIxJROeCySmM4+LXzmZlI5m5fex/wnc30VYkw1sugTtKVnvWKQjThduQolK6rvCX1YPydiGaG1T6w="
    - secure: "L9dKSo9jkFmUT+8N8jKL6ENllD1weHG04u9icIACgDxF6v2vYujzOXELLIjaILQ/eUsRbEM+QzO4TgpeFUhctE22nsHVSvsfzi7xqxpPpVw8gL0f3u+V0XmJM27n27sAOm3M31F38M5pVrzOuQZs2K+t3VPu4Jabo4GyGI/w/qQ="

